parameters:
    dp_repo.config.template_path: Designplug/Repository/RepositoryManagerBundle/Repository/config/templates
    dp_repo.config.database:
        database: %database_name%
        host: %database_host%
        driver: mysql
        username: %database_user%
        password: %database_password%
services:
    dp_repo.manager:
        class: Designplug\Repository\RepositoryManager
        arguments: [%dp_repo.config.repository_namespace%, %dp_repo.config.model_namespace%, %dp_repo.config.repository_initializer_namespace%]
        calls:
            - [setDatabaseManager, ["@dp_repo.database.manager"]]
    dp_repo.database.manager:
        class: Designplug\Repository\RepositoryManagerBundle\Database\DatabaseManager
        calls:
            - [setConnectionParameters, [%dp_repo.config.database%]]
    dp_repo.manager.command:
        class: Designplug\Repository\RepositoryManagerBundle\Command\GenerateCommand
        calls:
            - [setConfigurationOptions, ["%dp_repo.config.template_path%", "%dp_repo.config.repository_namespace%", "%dp_repo.config.model_namespace%", "%dp_repo.config.repository_initializer_namespace%"]]
        tags: 
            - { name: console.command }
